version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  web:
    build: .
    container_name: flask_app
    command: ["python", "app.py"]
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
      
networks:
  mynetwork:

volumes:
  db_data: